# Generated by Django 2.2 on 2019-04-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('director', models.CharField(max_length=80)),
                ('star', models.CharField(max_length=80)),
                ('comment', models.CharField(max_length=80)),
            ],
        ),
    ]
